version: '3.9'

services:
  postgres:
    container_name: postgres-testx
    image: postgres:15.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
