version: '3.9'

services:
  postgres-agency-test:
    container_name: postgres-agency-test
    image: postgres:15.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
